apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::240835895323:user/Jenkins
      username: Admin
      groups:
        - system:masters