apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-in-existing-vpc-20-mar
  region: ap-southeast-1

vpc:
  subnets:
    private:
      ap-southeast-1a: { id: subnet-0f3e5f2cc74ddcf50 }
      ap-southeast-1b: { id: subnet-0ddedf39d43a0a678 }

managedNodeGroups:
  - name: managed-ng-1
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
    volumeSize: 20
    privateNetworking: true
    labels: {role: worker}
    subnets:
      - subnet-0f3e5f2cc74ddcf50
      - subnet-0ddedf39d43a0a678
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true

