apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-in-existing-vpc
  region: ap-southeast-1

vpc:
  subnets:
    private:
      ap-southeast-1a: { id: subnet-0685c34c598394391 }

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: t3.small
    desiredCapacity: 1
    privateNetworking: true
  - name: ng-2-builders
    labels: { role: builders }
    instanceType: t3.small
    desiredCapacity: 1
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true