apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-in-existing-vpc
  region: ap-southeast-1

vpc:
  subnets:
    private:
      ap-southeast-1a: { id: subnet-0464b6da25430cbb0 }
      ap-southeast-1b: { id: subnet-02b71baaa20b4cadf }

managedNodeGroups:
  - name: managed-ng-1
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
    volumeSize: 20
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/alvin-keypair.pem
      # new feature for restricting SSH access to certain AWS security group IDs
    labels: {role: worker}
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true

